### ISSUE TITLE
Error when trying to use plugin

### ISSUE THREAD

**Issue by JaneeKCZ** [MitjaNemec/Archive3DModels#2]
Hi, i have this problem. 

Traceback (most recent call last): File "C:\Users\janee\Documents\KiCacI\6.0\3rdparty\plugins\action_archive_3d_models.py", line 237, in Run loggersinfo("Char size: "+ repr(dIg_size.GetCharHeight())) 
AttributeError 'Size object has no attribute 'GetCharHeight' 

Application: KiCad editor DPS (64-bit)
Version: (6.0.9), release build
Libraries:
    wxWidgets 3.2.1
    libcurl/7.83.1-DEV Schannel zlib/1.2.12
Platform: Windows 11 (build 22000), 64-bit edition, 64 bit, Little endian, wxMSW
Build Info:
    Date: Oct 29 2022 23:44:28
    wxWidgets: 3.2.1 (wchar_t,wx containers)
    Boost: 1.79.0
    OCC: 7.6.0
    Curl: 7.83.1-DEV
    ngspice: 37
    Compiler: Visual C++ 1929 without C++ ABI
Build settings:
    KICAD_USE_OCC=ON
    KICAD_SPICE=ON

Thanks for any help :)

**Comment by MitjaNemec** [comment]
First of all thanks for reporting this. Even though I can test the backend code the GUI code is a real PIT to test, and I sometimes skip testing. In this case it was obviously a mistake.

Before the new version is published in PCM you might want to change the offending line (line 237 in action_archive_3d_models.py from 
```
    logger.info("Char size: " + repr(dlg_size.GetCharHeight()))
```
to 
```
        logger.info("Char size: " + repr(main_dlg.GetCharHeight()))
```
