### ISSUE TITLE
KiCad V7 not supported

### ISSUE THREAD

**Issue by Fuzzlix** [MitjaNemec/Archive3DModels#3]
The addon dont work in KiCad7 anymore.

**Comment by MitjaNemec** [comment]
Can you please provide more details. Did you get any error message? If you did, what message you've got? Which version of the plugin you've got installed? What is your OS version.

**Comment by mikhailmihalkov** [comment]
> Не могли бы вы предоставить более подробную информацию. Вы получили сообщение об ошибке? Если да, то какое сообщение вы получили? Какая версия плагина у вас установлена? Какая у вас версия ОС.

In kicad 7 changed api python I think you yourself need to try to run it to understand the errors

**Comment by mikhailmihalkov** [comment]
This applies to all platforms

**Comment by MitjaNemec** [comment]
Should work now
