### ISSUE TITLE
Kicad 8

### ISSUE THREAD

**Issue by dzid26** [MitjaNemec/Archive3DModels#7]
Update  https://github.com/MitjaNemec/Archive3DModels/blob/32f6c68540d026e93d7c2f8305d79dd0978e0403/metadata_source.json#L27

I tried it with v8 and it works.

**Comment by MitjaNemec** [comment]
Thanks for checking and reminding me. The release is available https://github.com/MitjaNemec/Archive3DModels/releases/tag/1.0.11 and a change to PCM is in the progress https://gitlab.com/kicad/addons/metadata/-/merge_requests/312
